version: "3.4"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
