version: "3"
services:
  mongodb:
    image: mongo_one_user_login
    ports:
      - "27017:27017"
    networks:
      - my-network

  app:
    image: one_user_login
    ports:
      - "4000:3000"
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network:
